const dresses = [
  {
    id: 1,
    name: "Elegant Ziti Dress",
    description: "A luxurious silk dress for special occasions.",
    price: "$120",
    colors: { ziti: "/zitirobe.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "ziti",
  },
  {
    id: 2,
    name: "Chic Summer Dress",
    description: "Lightweight cotton perfect for summer days.",
    price: "$90",
    colors: { ziti: "/ziti.jpeg", black: "/bleumarie.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "ziti",
  },
  {
    id: 3,
    name: "Classic Dress",
    description: "Timeless dress suitable for any event.",
    price: "$150",
    colors: { beige: "/beige.jpeg", maroon: "/hmar.jpeg", brown: "/9ahwi.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "beige",
  },
  {
    id: 5,
    name: "Elegant Brown Dress",
    description: "A luxurious silk dress for special occasions.",
    price: "$120",
    colors: { brown: "/brown.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "brown",
  },
  {
    id: 6,
    name: "Elegant Borgandi Dress",
    description: "A luxurious silk dress for special occasions.",
    price: "$120",
    colors: { burgundy: "/borgandi.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "burgundy",
  },
  {
    id: 7,
    name: "Elegant Black Dress",
    description: "A luxurious silk dress for special occasions.",
    price: "$120",
    colors: { black: "/khal.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "black",
  },
  {
    id: 8,
    name: "Elegant Gray Dress",
    description: "A luxurious silk dress for special occasions.",
    price: "$120",
    colors: { gray: "/gris.jpeg" },
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    defaultColor: "gray",
  },
]
